import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Liquid} from 'liquid-gooey';
const send=(action,value)=>window.chrome?.webview?.postMessage({action,value});
function App(){
 const [s,set]=useState({status:'正在连接本机…',names:[],selected:0,preview:'',busy:false,details:''});
 const [page,tab]=useState(0),[level,L]=useState(0),[motion,M]=useState(!matchMedia('(prefers-reduced-motion: reduce)').matches);
 useEffect(()=>{const fn=e=>set(e.data);window.chrome?.webview?.addEventListener('message',fn);send('ready');return()=>window.chrome?.webview?.removeEventListener('message',fn)},[]);
 return <main><header><div className="brand"><span className="drop"/> <div>SLIDE <b>EVOLUTION</b><small>你的桌面，你的风格</small></div></div><span className="badge">WINDOWS · PREVIEW</span></header>
 <section className="toolbar"><div><span className="eyebrow">PERSONAL SPACE</span><h1>让灵感，有自己的风景。</h1></div><div className="nav"><Liquid key={motion?"motion":page} fill="#d6f4e8" blur={6} contrast={18} shadow="0 4px 18px rgba(137,224,186,.18)"><Liquid.Item x={page*90} transition={motion?'smooth':undefined}><div className="nav-drop"/></Liquid.Item></Liquid><div className="nav-labels">{['皮肤库','使用帮助','设置'].map((n,i)=><button key={n} aria-pressed={page===i} className={page===i?'active':''} onClick={()=>tab(i)}>{n}</button>)}</div></div></section>
 {page===0?<div className="workspace"><aside className="glass"><div className="section-head">我的皮肤 <span>{s.names.length.toString().padStart(2,'0')}</span></div><div className="skin-list">{s.names.map((n,i)=><button disabled={s.busy} className={'skin '+(s.selected===i?'selected':'')} key={i} onClick={()=>{send('select',i);L(0)}}><span className="skin-icon">◈</span><div>{n}<small>六张画面 · EX 视频</small></div><span className="dot"/></button>)}</div><button className="outline import" disabled={s.busy} onClick={()=>send('import')}>＋ 导入皮肤 ZIP</button><p className="muted">把喜欢的系列带到桌面。<br/>支持你自己制作的皮肤包。</p></aside><section className="hero glass"><div className="art">{s.preview&&<img src={s.preview} alt="所选皮肤预览"/>}<div className="shade"/><span className="preview-tag">静态预览 / {level===6?'EX':`L${level+1}`}</span><div className="art-title"><span>YOUR NEXT SCENE</span><h2>{s.names[s.selected]||'选择你的皮肤'}</h2></div></div><div className="levels"><span>画面预览</span><div>{Array.from({length:7},(_,i)=><button key={i} aria-pressed={level===i} className={level===i?'chosen':''} onClick={()=>{L(i);send('preview',i)}}>{i===6?'EX':`L${i+1}`}</button>)}</div></div></section></div>:<section className="glass info"><span className="eyebrow">{page===1?'QUICK START':'PREFERENCES'}</span><h2>{page===1?'从这里，开始你的第一张皮肤。':'刚刚好的动效，舒服的日常。'}</h2>{page===1?<ol><li>选择皮肤，点击下方“启动换肤”。</li><li>保存工作并退出普通 Codex；本面板会自动继续。</li><li>在换肤窗口用原生滑块换图，闪电按钮进入 EX。</li><li>回到面板点击“结束换肤”，等待恢复普通 Codex。</li></ol>:<><label className="setting">水滴过渡动效 <input type="checkbox" checked={motion} onChange={e=>M(e.target.checked)}/></label><p>这是独立的 Windows 换肤面板。所有皮肤文件在本机读取。</p><button className="outline" disabled={s.busy} onClick={()=>send('uninstall')}>卸载换肤工具…</button><p className="muted">卸载前会再次确认，请先备份个人皮肤。</p></>}</section>}
 <footer className="glass"><div className="state"><i className={s.busy?'working':''}/><div><b>{s.busy?'换肤会话':'准备你的下一幕'}</b><p>{s.status}</p></div></div><button className={'primary '+(s.busy?'stop':'')} onClick={()=>send(s.busy?'stop':'start')}>{s.busy?'结束 / 取消等待':'启动换肤'} <span>↗</span></button></footer><details className="logs"><summary>运行详情与错误信息</summary><pre>{s.details||'暂无运行记录'}</pre></details></main>
}
createRoot(document.getElementById('root')).render(<App/>);
